import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { encode } from '../core/toon-serializer.js';
import { getConfig } from '../core/config-loader.js';
import { RollbackManager } from '../execution/rollback.js';
import { Sandbox } from '../execution/sandbox.js';
import type { AgentTask, AgentResult, IAgent } from './types.js';
import { AgentTaskSchema } from './types.js';

type OpType = 'file_write' | 'file_read' | 'code_exec' | 'pkg_install' | 'dir_list' | 'command';

const FILE_WRITE_PATTERNS = [
  /\b(?:create|write|make|generate|save|build)\b.*\b(?:file|page|document|script|html|css|js|py|website|site|app)\b/i,
  /\b(?:create|build|make)\s+(?:a\s+)?(?:new\s+)?(?:file|page|website|site|script|app)\b/i,
  /\b(?:create|build|make)\s+(?:a\s+)?[\w\s]+(?:website|site|page|app|landing)\b/i,
];

const FILE_READ_PATTERNS = [
  /\b(?:read|show|display|cat|print|open)\b.*\bfile\b/i,
  /\bread\s+(?:the\s+)?(?:contents?\s+of\s+)?/i,
];

const CODE_EXEC_PATTERNS = [
  /\b(?:run|execute)\b.*\b(?:code|script|program|python|node|bash)\b/i,
  /\brun\s+(?:it|this|the\s+(?:code|script))\b/i,
  /\b(?:and\s+)?run\s+it\b/i,
];

const PKG_INSTALL_PATTERNS = [
  /\b(?:install|add)\b.*\b(?:package|module|library|dependency)\b/i,
  /\bnpm\s+install\b/i,
  /\bpip\s+install\b/i,
];

const DIR_LIST_PATTERNS = [
  /\b(?:list|show|ls)\b.*\b(?:dir|directory|files|folder)\b/i,
];

function detectOp(brief: string): OpType {
  if (FILE_WRITE_PATTERNS.some(p => p.test(brief))) return 'file_write';
  if (CODE_EXEC_PATTERNS.some(p => p.test(brief))) return 'code_exec';
  if (FILE_READ_PATTERNS.some(p => p.test(brief))) return 'file_read';
  if (PKG_INSTALL_PATTERNS.some(p => p.test(brief))) return 'pkg_install';
  if (DIR_LIST_PATTERNS.some(p => p.test(brief))) return 'dir_list';
  return 'command';
}

function extractFilename(brief: string): string {
  const namePatterns = [
    /['"`]([^'"`]+\.[a-z]{2,4})['"`]/i,
    /called\s+(\S+\.\w+)/i,
    /named\s+(\S+\.\w+)/i,
    /file\s+(\S+\.\w+)/i,
    /create\s+(\S+\.\w+)/i,
    /write\s+(?:to\s+)?(\S+\.\w+)/i,
    /save\s+(?:as|to)\s+(\S+\.\w+)/i,
    /\b([\w-]+\.(?:html|css|js|ts|py|md|json|txt|sh))\b/i,
  ];
  for (const pattern of namePatterns) {
    const match = pattern.exec(brief);
    if (match?.[1]) return match[1];
  }
  return inferFilename(brief);
}

function extractCodeBlock(brief: string): { lang: string; code: string } | null {
  const blockMatch = /```(\w*)\n([\s\S]*?)```/.exec(brief);
  if (blockMatch) {
    return { lang: blockMatch[1] || 'text', code: blockMatch[2] ?? '' };
  }
  return null;
}

function detectLanguage(brief: string): string {
  const lower = brief.toLowerCase();
  if (lower.includes('python') || lower.includes('.py')) return 'python';
  if (lower.includes('node') || lower.includes('javascript') || lower.includes('.js')) return 'node';
  if (lower.includes('bash') || lower.includes('shell') || lower.includes('.sh')) return 'bash';
  return 'node';
}

function extractContentFromBrief(brief: string): string {
  const codeBlock = extractCodeBlock(brief);
  if (codeBlock) return codeBlock.code;

  const contentMatch = /(?:with|containing|content[:\s]+)([\s\S]+)/i.exec(brief);
  if (contentMatch?.[1]) return contentMatch[1].trim();

  return '';
}

function inferFilename(brief: string): string {
  const lower = brief.toLowerCase();
  if (lower.includes('html') || lower.includes('website') || lower.includes('web page') || lower.includes('site') || lower.includes('landing')) return 'index.html';
  if (lower.includes('python') || lower.includes('.py')) return 'main.py';
  if (lower.includes('javascript') || lower.includes('.js')) return 'main.js';
  if (lower.includes('typescript') || lower.includes('.ts')) return 'main.ts';
  if (lower.includes('css') || lower.includes('style')) return 'styles.css';
  if (lower.includes('readme') || lower.includes('.md')) return 'README.md';
  return 'output.txt';
}

function extractTopic(brief: string): string {
  const match = /(?:for|about|called|named|a)\s+([\w\s]+?)(?:\s+with|\s+that|\s+using|$)/i.exec(brief);
  return match?.[1]?.trim() ?? 'MicroClaw Project';
}

function generateContent(brief: string, filename: string): string {
  const ext = path.extname(filename).toLowerCase();
  const topic = extractTopic(brief);

  if (ext === '.html') return generateHTML(brief, topic);
  if (ext === '.css') return `/* ${topic} styles */\n* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: system-ui, sans-serif; }\n`;
  if (ext === '.py') return `#!/usr/bin/env python3\n# ${topic}\n\ndef main():\n    print("Hello from ${filename}")\n\nif __name__ == "__main__":\n    main()\n`;
  if (ext === '.js' || ext === '.ts') return `// ${topic}\nconsole.log("Hello from ${filename}");\n`;
  if (ext === '.md') return `# ${topic}\n\nGenerated by MicroClaw.\n`;
  return `${topic}\n`;
}

function generateHTML(brief: string, topic: string): string {
  const lower = brief.toLowerCase();

  if (lower.includes('coffee') || lower.includes('cafe') || lower.includes('brew')) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${topic}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', serif; background: #1a0a00; color: #f5e6d0; }
    header { background: #2d1a0e; padding: 60px 20px; text-align: center; border-bottom: 3px solid #8b4513; }
    header h1 { font-size: 3rem; color: #d4a96a; letter-spacing: 4px; text-transform: uppercase; }
    header p { margin-top: 12px; font-size: 1.1rem; color: #a07850; font-style: italic; }
    nav { background: #3d1f0a; display: flex; justify-content: center; gap: 40px; padding: 16px; }
    nav a { color: #d4a96a; text-decoration: none; font-size: 0.95rem; letter-spacing: 2px; text-transform: uppercase; transition: color 0.2s; }
    nav a:hover { color: #fff; }
    .hero { background: linear-gradient(rgba(26,10,0,0.7), rgba(26,10,0,0.7)), url('https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1400') center/cover; padding: 120px 20px; text-align: center; }
    .hero h2 { font-size: 2.5rem; color: #f5e6d0; margin-bottom: 16px; }
    .hero p { font-size: 1.1rem; color: #c4a070; max-width: 500px; margin: 0 auto 30px; }
    .btn { background: #8b4513; color: #fff; padding: 14px 36px; border: none; font-size: 1rem; letter-spacing: 2px; text-transform: uppercase; cursor: pointer; transition: background 0.2s; text-decoration: none; display: inline-block; }
    .btn:hover { background: #a0522d; }
    .menu { padding: 80px 20px; max-width: 900px; margin: 0 auto; text-align: center; }
    .menu h2 { font-size: 2rem; color: #d4a96a; margin-bottom: 50px; letter-spacing: 3px; }
    .menu-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 30px; }
    .menu-item { background: #2d1a0e; padding: 30px 20px; border-radius: 4px; border: 1px solid #5a3020; }
    .menu-item h3 { color: #d4a96a; font-size: 1.2rem; margin-bottom: 10px; }
    .menu-item p { color: #a07850; font-size: 0.9rem; }
    .price { color: #d4a96a; font-size: 1.1rem; font-weight: bold; margin-top: 12px; }
    footer { background: #2d1a0e; text-align: center; padding: 30px; color: #7a5535; border-top: 1px solid #5a3020; }
  </style>
</head>
<body>
  <header>
    <h1>The Daily Grind</h1>
    <p>Artisan coffee, roasted with passion</p>
  </header>
  <nav>
    <a href="#">Home</a>
    <a href="#">Menu</a>
    <a href="#">Our Story</a>
    <a href="#">Contact</a>
  </nav>
  <div class="hero">
    <h2>Every Cup Tells a Story</h2>
    <p>Ethically sourced beans, expertly roasted, served with care.</p>
    <a href="#menu" class="btn">View Our Menu</a>
  </div>
  <section class="menu" id="menu">
    <h2>Our Menu</h2>
    <div class="menu-grid">
      <div class="menu-item">
        <h3>Espresso</h3>
        <p>A perfect single shot of our house blend</p>
        <div class="price">$3.50</div>
      </div>
      <div class="menu-item">
        <h3>Flat White</h3>
        <p>Velvety microfoam over a double ristretto</p>
        <div class="price">$5.00</div>
      </div>
      <div class="menu-item">
        <h3>Pour Over</h3>
        <p>Single origin, brewed to order</p>
        <div class="price">$6.00</div>
      </div>
      <div class="menu-item">
        <h3>Cold Brew</h3>
        <p>12-hour steeped, smooth and strong</p>
        <div class="price">$5.50</div>
      </div>
    </div>
  </section>
  <footer>
    <p>&copy; 2025 The Daily Grind &mdash; Open Mon-Sun 7am-8pm</p>
  </footer>
</body>
</html>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${topic}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: #f5f5f5; color: #333; }
    header { background: #1a1a2e; color: #fff; padding: 40px 20px; text-align: center; }
    header h1 { font-size: 2.5rem; }
    header p { margin-top: 10px; opacity: 0.8; }
    main { max-width: 900px; margin: 60px auto; padding: 0 20px; }
    .card { background: #fff; border-radius: 8px; padding: 40px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); margin-bottom: 30px; }
    h2 { color: #1a1a2e; margin-bottom: 16px; }
    p { line-height: 1.7; color: #555; }
    footer { text-align: center; padding: 30px; color: #888; }
  </style>
</head>
<body>
  <header>
    <h1>${topic}</h1>
    <p>Built with MicroClaw</p>
  </header>
  <main>
    <div class="card">
      <h2>Welcome</h2>
      <p>This is your ${topic} website. Edit this file to add your content.</p>
    </div>
  </main>
  <footer>&copy; 2025 ${topic}</footer>
</body>
</html>`;
}

function extractPackageName(brief: string): { manager: string; pkg: string } {
  const npmMatch = /npm\s+install\s+(\S+)/i.exec(brief);
  if (npmMatch?.[1]) return { manager: 'npm', pkg: npmMatch[1] };

  const pipMatch = /pip\s+install\s+(\S+)/i.exec(brief);
  if (pipMatch?.[1]) return { manager: 'pip', pkg: pipMatch[1] };

  const pkgMatch = /install\s+(\S+)/i.exec(brief);
  if (pkgMatch?.[1]) {
    const name = pkgMatch[1];
    const isPython = brief.toLowerCase().includes('python') || brief.toLowerCase().includes('pip');
    return { manager: isPython ? 'pip' : 'npm', pkg: name };
  }

  return { manager: 'npm', pkg: '' };
}

export class ExecutionAgent implements IAgent {
  readonly type = 'execution' as const;
  private readonly rollback: RollbackManager;
  private readonly sandbox: Sandbox;

  constructor() {
    this.rollback = new RollbackManager();
    const config = getConfig();
    this.sandbox = new Sandbox({
      preferredRuntime: config.executionMode === 'isolated' ? 'docker' : 'none',
      allowDirectExec: config.executionMode === 'full_control',
    });
  }

  async execute(task: AgentTask): Promise<AgentResult> {
    const validated = AgentTaskSchema.parse(task);
    const start = performance.now();
    const brief = validated.brief;
    const op = detectOp(brief);

    let command = '';
    let exitCode = 0;
    let stdout = '';
    let stderr = '';
    const filesCreated: string[] = [];

    try {
      switch (op) {
        case 'file_write': {
          const filename = extractFilename(brief);
          const rawContent = extractContentFromBrief(brief);
          const content = rawContent || generateContent(brief, filename);
          const filePath = path.resolve(filename);

          await this.rollback.withRollback(async () => {
            const dir = path.dirname(filePath);
            fs.mkdirSync(dir, { recursive: true });
            fs.writeFileSync(filePath, content, 'utf-8');
          }, [filePath]);

          command = `write ${filename}`;
          stdout = `Created ${filename} (${content.length} bytes)`;
          filesCreated.push(filename);
          break;
        }

        case 'file_read': {
          const filename = extractFilename(brief);
          const filePath = path.resolve(filename);
          if (!fs.existsSync(filePath)) {
            exitCode = 1;
            stderr = `File not found: ${filename}`;
          } else {
            stdout = fs.readFileSync(filePath, 'utf-8');
            command = `read ${filename}`;
          }
          break;
        }

        case 'code_exec': {
          const codeBlock = extractCodeBlock(brief);
          const lang = codeBlock?.lang || detectLanguage(brief);
          const code = codeBlock?.code || extractContentFromBrief(brief);
          const ext = lang === 'python' ? '.py' : lang === 'bash' ? '.sh' : '.js';
          const tmpFile = path.join(process.cwd(), `_microclaw_tmp${ext}`);

          fs.writeFileSync(tmpFile, code, 'utf-8');
          filesCreated.push(tmpFile);

          const config = getConfig();
          if (config.executionMode === 'isolated') {
            try {
              const result = await this.sandbox.exec(
                `${lang === 'python' ? 'python3' : lang === 'bash' ? 'bash' : 'node'} ${tmpFile}`,
              );
              stdout = result.stdout;
              stderr = result.stderr;
              exitCode = result.exitCode;
            } catch {
              const runner = lang === 'python' ? 'python3' : lang === 'bash' ? 'bash' : 'node';
              const result = spawnSync(runner, [tmpFile], {
                timeout: 30_000,
                encoding: 'utf-8',
                cwd: process.cwd(),
              });
              stdout = result.stdout ?? '';
              stderr = result.stderr ?? '';
              exitCode = result.status ?? 1;
            }
          } else {
            const runner = lang === 'python' ? 'python3' : lang === 'bash' ? 'bash' : 'node';
            const result = spawnSync(runner, [tmpFile], {
              timeout: 30_000,
              encoding: 'utf-8',
              cwd: process.cwd(),
            });
            stdout = result.stdout ?? '';
            stderr = result.stderr ?? '';
            exitCode = result.status ?? 1;
          }

          command = `${lang} ${tmpFile}`;
          try { fs.unlinkSync(tmpFile); } catch { /* already cleaned up */ }
          break;
        }

        case 'pkg_install': {
          const { manager, pkg } = extractPackageName(brief);
          if (!pkg) {
            exitCode = 1;
            stderr = 'Could not determine package name';
            break;
          }
          const args = manager === 'npm' ? ['install', pkg] : ['install', pkg];
          const result = spawnSync(manager === 'npm' ? 'npm' : 'pip3', args, {
            timeout: 120_000,
            encoding: 'utf-8',
            cwd: process.cwd(),
          });
          stdout = result.stdout ?? '';
          stderr = result.stderr ?? '';
          exitCode = result.status ?? 1;
          command = `${manager} install ${pkg}`;
          break;
        }

        case 'dir_list': {
          const dirMatch = /(?:list|show|ls)\s+(\S+)/i.exec(brief);
          const targetDir = dirMatch?.[1] ?? '.';
          const resolved = path.resolve(targetDir);
          if (!fs.existsSync(resolved)) {
            exitCode = 1;
            stderr = `Directory not found: ${targetDir}`;
          } else {
            const entries = fs.readdirSync(resolved, { withFileTypes: true });
            stdout = entries
              .map(e => `${e.isDirectory() ? 'd' : 'f'} ${e.name}`)
              .join('\n');
            command = `ls ${targetDir}`;
          }
          break;
        }

        case 'command': {
          const cmdMatch = /(?:run|execute)\s+[`"']?(.*?)[`"']?\s*$/i.exec(brief);
          const cmd = cmdMatch?.[1] ?? brief;
          const config = getConfig();
          if (config.executionMode === 'isolated') {
            try {
              const result = await this.sandbox.exec(cmd);
              stdout = result.stdout;
              stderr = result.stderr;
              exitCode = result.exitCode;
            } catch {
              const result = spawnSync('sh', ['-c', cmd], {
                timeout: 30_000,
                encoding: 'utf-8',
                cwd: process.cwd(),
              });
              stdout = result.stdout ?? '';
              stderr = result.stderr ?? '';
              exitCode = result.status ?? 1;
            }
          } else {
            const result = spawnSync('sh', ['-c', cmd], {
              timeout: 30_000,
              encoding: 'utf-8',
              cwd: process.cwd(),
            });
            stdout = result.stdout ?? '';
            stderr = result.stderr ?? '';
            exitCode = result.status ?? 1;
          }
          command = cmd;
          break;
        }
      }
    } catch (err) {
      exitCode = 1;
      stderr = err instanceof Error ? err.message : String(err);
    }

    const output = encode('exec_result', {
      command,
      exitCode,
      stdout,
      stderr,
      filesCreated,
    } as Record<string, unknown>);

    const durationMs = performance.now() - start;

    return {
      taskId: validated.id,
      agentType: this.type,
      output,
      tokensUsed: Math.ceil(output.length / 4),
      durationMs,
    };
  }
}
